### ISSUE TITLE
Does not working with firebase function

### ISSUE THREAD

**Issue by ARPNetBR** [shtaif/multerator#62]
Hello, I'm trying to upload a PDF file with Ionic to Node.js but I'm getting the same error I used to get with Multer. The error message I'm seeing is: "Invalid multipart payload format; stream ended unexpectedly without a closing boundary". As a result, the upload is not successful and the "success" variable is set to "false".

**Comment by shtaif** [comment]
Hi @ARPNetBR 😄

Do you have some reproducible code sample to share, or perhaps the raw contents of the input stream? or any other practical details helpful for figuring this out?

Thanks for reaching out ✌🏻

**Comment by shtaif** [comment]
Been stale here - if you see a reason to continue please reopen 🤞🏻
